### ISSUE TITLE
Are you missing some texts in PostPrefix.english.php?

### ISSUE THREAD

**Issue by tuivodich** [DiegoCortes/SMF-Post-Prefix#2]
Hi, are you missing some texts in PostPrefix.english.php? It causes some "Undefined index" errors logs at PostPrefix settings page.
Here maybe some texts that we need in **PostPrefix.english.php**: 

> // Settings page
> $txt['PostPrefix_enable_filter'] = 'Filter Post Prefix';
> $txt['PostPrefix_enable_filter_desc'] = 'Use this option to filter your post prefix';
> $txt['PostPrefix_select_order'] = 'Order by';
> $txt['PostPrefix_select_order_desc'] = 'Select filter order';
> $txt['PostPrefix_prefix_id'] = 'ID';
> $txt['PostPrefix_select_order_dir'] = 'Order direction';
> $txt['PostPrefix_select_order_dir_desc'] = 'Select filter order by direction';
> $txt['PostPrefix_DESC'] = 'DESC';
> $txt['PostPrefix_ASC'] = 'ASC';

**Comment by DiegoAndresCortes** [comment]
mod is yet to be completed, probably not working properly haven't tested it

**Comment by DiegoAndresCortes** [comment]
Just a side note, I will start to work on this again soon

**Comment by tuivodich** [comment]
I’m looking forward to getting your news! Hope it will work soon!

**Comment by DiegoAndresCortes** [comment]
mod is finished, working on SMF 2.1 RC3 or github build of SMF.
No SMF 2.1 RC2 support

**Comment by DiegoAndresCortes** [comment]
Also feel free to contribute any translation

**Comment by tuivodich** [comment]
It's a good news! I'm using the latest SMF 2.1 on github and will use this mod, too!
